import type { Flavor } from '@/shared/types/glossier'

export const FLAVORS: Flavor[] = [
  {
    id: 'original',
    name: 'Original',
    description: 'Fragrance-free, untinted.',
    color: '#F5F5F5',
    labelColor: '#000',
    tubeColor: '#FFFFFF',
    capColor: '#FFB6C1',
  },
  {
    id: 'rose',
    name: 'Rose',
    description: 'Fizzy rose with a shimmery baby pink tint.',
    color: '#FBCFE8',
    labelColor: '#000',
    tubeColor: '#FBCFE8',
    capColor: '#F472B6',
  },
  {
    id: 'birthday',
    name: 'Birthday',
    description: 'Vanilla buttercream cake with subtle shimmer.',
    color: '#E5E7EB',
    labelColor: '#000',
    tubeColor: '#E5E5E5',
    capColor: '#FCD34D',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    description: 'Sweet strawberry with a jammy red tint.',
    color: '#EF4444',
    labelColor: '#FFF',
    tubeColor: '#EF4444',
    capColor: '#FECACA',
  },
  {
    id: 'mint',
    name: 'Mint',
    description: 'Cooling menthol with a clear finish.',
    color: '#A7F3D0',
    labelColor: '#000',
    tubeColor: '#A7F3D0',
    capColor: '#34D399',
  },
  {
    id: 'coconut',
    name: 'Coconut',
    description: 'Beach vacation with a clear finish.',
    color: '#FDE68A',
    labelColor: '#000',
    tubeColor: '#FDE68A',
    capColor: '#D97706',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Bright floral with a sheer purple tint.',
    color: '#C4B5FD',
    labelColor: '#000',
    tubeColor: '#C4B5FD',
    capColor: '#7C3AED',
  },
  {
    id: 'mango',
    name: 'Mango',
    description: 'Fresh and juicy with a translucent coral tint.',
    color: '#FB923C',
    labelColor: '#000',
    tubeColor: '#FB923C',
    capColor: '#F87171',
  },
  {
    id: 'wildfig',
    name: 'Wild Fig',
    description: 'Jammy fruit with a deep coral tint.',
    color: '#9F1239',
    labelColor: '#FFF',
    tubeColor: '#9F1239',
    capColor: '#BE123C',
  },
]

